# Adapted from https://github.com/hvr/multi-ghc-travis

# NB: don't set `language: haskell` here.
language: c

# Request Ubuntu Trusty (14.04 LTS).
dist: trusty

# Explicitly request sudo-enabled virtual environments
sudo: required

##############################################################################
# Tests

matrix:
  include:
    - env: TEST=MAIN GHC_VER=8.2.1 BUILD=CABAL CABAL_VER=2.0
      addons:
        apt:
          packages:
            - alex-3.1.7
            - cabal-install-2.0
            - ghc-8.2.1
            - happy-1.19.5
            - texlive-binaries
          sources:
            - hvr-ghc

    - env: TEST=main GHC_VER=8.0.2 CABAL_VER=1.24
      addons:
        apt:
          packages:
            - alex-3.1.7
            - cabal-install-1.24
            - ghc-8.0.2
            - happy-1.19.5
            - texlive-binaries
          sources:
            - hvr-ghc

    - env: TEST=main GHC_VER=7.10.3 CABAL_VER=1.22
      addons:
        apt:
          packages:
            - alex-3.1.7
            - cabal-install-1.22
            - ghc-7.10.3
            - happy-1.19.5
          sources:
            - hvr-ghc

##############################################################################
before_install:
  - export APIA_HOME=`pwd`
  - export MY_HOME=${HOME}/build/asr
  - mkdir ${MY_HOME}/bin
  - export PATH=${MY_HOME}/bin:/opt/ghc/${GHC_VER}/bin:/opt/cabal/${CABAL_VER}/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:${PATH}

##############################################################################
install:
  # How much memory we have.
  - vmstat -s

  # Asking for the shell.
  - echo $SHELL

  - cabal --version
  - ghc --version
  - cabal update
  - cat ${HOME}/.cabal/config
  - if [[ $CABAL_VER = "1.18" ]]; then
       cabal install cabal-install;
    fi
  - export PATH=${HOME}/.cabal/bin:${PATH}
  - cabal --version
  - export JOBS=2

##############################################################################
# Installing the extended version of Agda (adapted from Agda)

  # The version installed of cpphs should match the lower version
  # required in apia.cabal.
  - cabal install cpphs-1.20.8

  - git clone https://github.com/asr/eagda.git ${MY_HOME}/eagda
  - cd ${MY_HOME}/eagda
  - cabal install --only-dependencies --force-reinstalls
  - cabal configure -v2
  - cabal build -v2 -j${JOBS}
  - cabal copy
  - cabal register
  - cd ${APIA_HOME}

##############################################################################
# Installing Apia

  - cabal install -v2 -j${JOBS} --enable-tests

##############################################################################
# Installing tptp4X

  - cp tools/tptp4X ${MY_HOME}/bin/

##############################################################################
# Installing fix-whitespace

  - make install-fix-whitespace

##############################################################################
# Installing HLint and shelltestrunner

  - cabal install hlint

# We used `--allow-newer=process` because
# https://github.com/simonmichael/shelltestrunner/pull/8.
  - cabal install shelltestrunner --allow-newer=process

##############################################################################
# Installing the E theorem prover

  - cd ${MY_HOME}
  - wget http://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_2.0/E.tgz
  - tar -xzf E.tgz
  - cd E
  - ./configure --bindir=${MY_HOME}/bin
  - make
  - make install
  - cd ${APIA_HOME}

##############################################################################
# Installing OnlineATPs

  - git clone https://github.com/jonaprieto/online-atps ${MY_HOME}/online-atps
  - cd ${MY_HOME}/online-atps
  - cabal install --force-reinstalls
  - cd ${APIA_HOME}

##############################################################################
script:

  - make generated-all
  - make non-conjectures
  - make errors
  - make type-check-notes
  - make ATPs="e" prove-notes
  - make check-whitespace
  - make hlint

branches:
  only:
    - master
